sudo: required
services:
  - docker

before_install:
  - docker build -t dimitriosd/cicd-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dimitriosd/cicd-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "cicd-react"
  env: "CicdReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-226761018526"
  bucket_path: "cicd-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
